### ISSUE TITLE
Rcoket League Set Up

### ISSUE THREAD

**Issue by pfalrey** [RocketLeagueMapmaking/UDK_RL_Setup#1]
For some reason, even though I renamed the setup folder to RocketLeagueMapMaking, every time I get to the 3rd step of the setup, it says that I'm not in the install location, even though I always am. Could/would you please help?

**Comment by spencerarrasmith** [comment]
Can you paste the contents of log.txt? The script simply looks for files to make sure it creates shortcuts properly, so if it's not seeing them then they aren't there.

**Comment by pfalrey** [comment]
im not entirely sure how to do that

**Comment by spencerarrasmith** [comment]
![image](https://user-images.githubusercontent.com/1505402/106981651-9ec09380-671f-11eb-942e-35b64b9c8c89.png)

Open this file, select all, copy, paste

**Comment by pfalrey** [comment]
printed step 2 text 
udkinstalled: y 
udkdir: n 
udkdir: n 
udkdir: n

**Comment by spencerarrasmith** [comment]
What are you typing when it asks for "Enter Install Location, including the Project Name: "?

Can you paste a screenshot of the contents of that folder?

**Comment by pfalrey** [comment]
I dont type anything. I just press enter

**Comment by pfalrey** [comment]
![Screenshot 2021-02-06 233457](https://user-images.githubusercontent.com/78554873/107136789-454d9580-68d4-11eb-8e7c-d6e0f0c6adef.png)

**Comment by spencerarrasmith** [comment]
On that line, please type `C:\UDK\Custom`

**Comment by pfalrey** [comment]
which line?

**Comment by spencerarrasmith** [comment]
Are you in the Discord server? I can help you out much more quickly there.

Technically you should only open github issues for things that are wrong with the code, but I don't think that is what's happening here.

**Comment by pfalrey** [comment]
yes im in the discord server

**Comment by pfalrey** [comment]
im cptcomeback
